tap "homebrew/core"

##################################################################
#                         *Python Tools*                         #
##################################################################

# CLI Tools

brew "ipython"
brew "pre-commit"
brew "poetry"
brew "cookiecutter"
brew "pyinvoke"
brew "bumpversion"
brew "twine-pypi"
brew "tox"
brew "nox"
brew "jupyterlab"
brew "virtualenvwrapper"

# pyenv and related plugins

brew "pyenv"
brew "pyenv-ccache"
brew "pyenv-virtualenvwrapper"
brew "pyenv-pip-migrate"
